### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by xiehan** [cvuorinen/phpdoc-markdown-public#2]
I'm interested in this project, but can't get it to actually output documentation. All I get is:

```
Preparing template "vendor/cvuorinen/phpdoc-markdown-public/data/t .. 

  [Symfony\Component\Filesystem\Exception\IOException]                                                                 
  Failed to create "/Users/{redacted}/vendor/phpdocumentor/phpdocumentor/src/ph  
  pDocumentor/Transformer/../../../data/templates/markdown-public": Undefined variable: undefinedVariable.             
```

**Comment by quantumpacket** [comment]
Can you provide a minimal example file that is causing the above error?

**Comment by thorakmedichi** [comment]
I get the same error as well

**Comment by cvuorinen** [comment]
@thorakmedichi can you provide a little more info? Like the command you executed and the `phpdoc.xml` configuration if you have any?

**Comment by thorakmedichi** [comment]
I managed to solve it already. Thanks anyways
